prgrms-web-devcourse/Team_09_p2p_BE

appspec.yml, scripts/deploy.sh
=> setting: jenkins 설정

appspec.yml
=> [P2P-10] docs: appspec.yml 파일 수정

src/main/java/com/prgrms/p2p/domain/bookmark/entity/Bookmark.java, src/main/java/com/prgrms/p2p/domain/bookmark/entity/CourseBookmark.java, src/main/java/com/prgrms/p2p/domain/bookmark/entity/PlaceBookmark.java, src/main/java/com/prgrms/p2p/domain/comment/entity/Comment.java, src/main/java/com/prgrms/p2p/domain/comment/entity/CourseComment.java, src/main/java/com/prgrms/p2p/domain/comment/entity/PlaceComment.java, src/main/java/com/prgrms/p2p/domain/common/BaseEntity.java, src/main/java/com/prgrms/p2p/domain/course/entity/Course.java, src/main/java/com/prgrms/p2p/domain/course/entity/CoursePlace.java, src/main/java/com/prgrms/p2p/domain/course/entity/Period.java, src/main/java/com/prgrms/p2p/domain/course/entity/Region.java, src/main/java/com/prgrms/p2p/domain/course/entity/Theme.java, src/main/java/com/prgrms/p2p/domain/like/entity/CourseLike.java, src/main/java/com/prgrms/p2p/domain/like/entity/Like.java, src/main/java/com/prgrms/p2p/domain/like/entity/PlaceLike.java, src/main/java/com/prgrms/p2p/domain/place/entity/Address.java, src/main/java/com/prgrms/p2p/domain/place/entity/Category.java, src/main/java/com/prgrms/p2p/domain/place/entity/PhoneNumber.java, src/main/java/com/prgrms/p2p/domain/place/entity/Place.java, src/main/java/com/prgrms/p2p/domain/user/entity/Sex.java, src/main/java/com/prgrms/p2p/domain/user/entity/User.java
주목할 부분
1. BookmarkCourse or CourseBookmark ?? 비슷한 클래스들의 네이밍 관련
2. CoursePlace의 Linked List 구현 적합한지? (todo 참조)
3. 연관관계 어노테이션의 적합한 사용 (다 대 일, 일 대 다, cascade, fetch, orphanRemoval 의 누락이나 실수부분)
=> [P2P-141] 기본 Entity 구성입니다.

build.gradle, src/main/java/com/prgrms/p2p/domain/common/service/UploadService.java, src/main/java/com/prgrms/p2p/domain/common/service/UploadServiceImpl.java, src/test/java/com/prgrms/p2p/common/localStack/LocalStackS3Config.java
=> [P2P - 142~144] queryDsl, awsS3, LocalStack 적용

src/main/java/com/prgrms/p2p/domain/bookmark/entity/Bookmark.java, src/main/java/com/prgrms/p2p/domain/bookmark/entity/CourseBookmark.java, src/main/java/com/prgrms/p2p/domain/bookmark/entity/PlaceBookmark.java, src/main/java/com/prgrms/p2p/domain/comment/entity/Comment.java, src/main/java/com/prgrms/p2p/domain/comment/entity/CourseComment.java, src/main/java/com/prgrms/p2p/domain/comment/entity/PlaceComment.java, src/main/java/com/prgrms/p2p/domain/course/entity/Course.java, src/main/java/com/prgrms/p2p/domain/course/entity/CoursePlace.java, src/main/java/com/prgrms/p2p/domain/course/entity/Region.java, src/main/java/com/prgrms/p2p/domain/course/entity/Theme.java, src/main/java/com/prgrms/p2p/domain/like/entity/CourseLike.java, src/main/java/com/prgrms/p2p/domain/like/entity/Like.java, src/main/java/com/prgrms/p2p/domain/like/entity/PlaceLike.java, src/main/java/com/prgrms/p2p/domain/place/entity/Category.java, src/main/java/com/prgrms/p2p/domain/place/entity/Place.java, src/main/java/com/prgrms/p2p/domain/user/entity/User.java
=> [P2P-12] Entity column, 생성자, 연관관계 매핑, 수정 로직 등을  추가했습니다.

src/main/java/com/prgrms/p2p/domain/user/entity/repository/UserRepository.java, src/main/java/com/prgrms/p2p/domain/user/entity/service/CustomUserDetailService.java
- UserRepository 추가
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-20] feat: UserRepository 추가

src/main/java/com/prgrms/p2p/domain/course/entity/Course.java, src/main/java/com/prgrms/p2p/domain/course/entity/CoursePlace.java, src/main/java/com/prgrms/p2p/domain/course/repository/CoursePlaceRepository.java, src/main/java/com/prgrms/p2p/domain/place/controller/PlaceController.java, src/main/java/com/prgrms/p2p/domain/place/dto/CreatePlaceRequest.java, src/main/java/com/prgrms/p2p/domain/place/dto/DetailPlaceResponse.java, src/main/java/com/prgrms/p2p/domain/place/entity/Address.java, src/main/java/com/prgrms/p2p/domain/place/entity/Place.java, src/main/java/com/prgrms/p2p/domain/place/repository/PlaceRepository.java, src/main/java/com/prgrms/p2p/domain/place/service/PlaceService.java, src/main/java/com/prgrms/p2p/domain/place/util/PlaceConverter.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-64] feat: 7/29일 작업 내용 place 등록 조회 및 CoursePlace 로직 변경

.gitignore, src/test/resources/application.yaml
- 편한 개발환경을 위하여 테스트를 위한 yaml 파일을 추가합니다.
- yaml 파일 예전에 사용했던 걸로 올림..
- 없음
=> [P2P-149] gitignore 설정 추가

src/main/java/com/prgrms/p2p/domain/common/BaseEntity.java, src/main/java/com/prgrms/p2p/domain/like/entity/Like.java, src/main/java/com/prgrms/p2p/domain/like/entity/PlaceLike.java, src/main/java/com/prgrms/p2p/domain/like/repository/PlaceLikeRepository.java, src/main/java/com/prgrms/p2p/domain/like/service/PlaceLikeService.java, src/main/java/com/prgrms/p2p/domain/like/service/SimplePlaceLikeService.java, src/test/java/com/prgrms/p2p/domain/like/service/PlaceLikeServiceTest.java
- 장소의 상세 정보와, 목록정보를 조회할 때 좋아요 정보가 필요합니다.
- 따라서 기존에 계획했던 순서를 수정하여 좋아요 부터 개발하게 되었습니다.
- 좋아요를 토글하는 기능을 구현하였습니다.
- 기능이 제대로 동작하는지 확인하기 위해, Mocking으로 로직 확인에 집중하였습니다.
- Entity 테스트와 Repository 테스트는 추후 구현할 예정입니다.
- 엔티티 설정이 잘못된 것이 있어 수정하였습니다.
- API를 위한 Controller 단은 사용자 토큰인증이 완료된 후에 붙일 예정입니다.
- Service 테스트에서 놓친 부분이 있는지
- 타 도메인이거나, 다른 클래스의 예외는 다른 테스트 코드에서 구현해야함.
=> [P2P-107] 사용자가 장소에 좋아요를 토글 할 수 있습니다.

src/main/java/com/prgrms/p2p/domain/like/entity/CourseLike.java, src/main/java/com/prgrms/p2p/domain/like/entity/Like.java, src/main/java/com/prgrms/p2p/domain/like/entity/PlaceLike.java, src/main/java/com/prgrms/p2p/domain/like/repository/PlaceLikeRepository.java, src/main/java/com/prgrms/p2p/domain/like/service/SimplePlaceLikeService.java, src/test/java/com/prgrms/p2p/domain/like/entity/PlaceLikeTest.java, src/test/java/com/prgrms/p2p/domain/like/repository/PlaceLikeRepositoryTest.java, src/test/java/com/prgrms/p2p/domain/like/service/PlaceLikeServiceTest.java
- 엔티티와 레포지토리, 세세한 오류사항을 수정하였습니다.
- 엔티티가 잘못만들어져 있어서 발생한 Context 업로드 오류를 해결하고, 엔티티와 레포지토리 테스트를 추가하였습니다.
- 엔티티는 생성 로직 확인, 레포지토리는 정상동작 여부 테스트에 초점을 두었습니다.
- 태스트 코드!
=> [P2P-108] 장소 좋아요 추가/삭제 기능에 대한 테스트를 추가합니다.

src/main/java/com/prgrms/p2p/domain/user/controller/UserController.java, src/main/java/com/prgrms/p2p/domain/user/dto/SignUpRequest.java, src/main/java/com/prgrms/p2p/domain/user/entity/User.java, src/main/java/com/prgrms/p2p/domain/user/service/UserService.java, src/main/java/com/prgrms/p2p/domain/user/util/Validation.java, src/test/java/com/prgrms/p2p/domain/user/entity/UserTest.java, src/test/java/com/prgrms/p2p/domain/user/service/UserServiceTest.java, src/test/java/com/prgrms/p2p/domain/user/util/ValidationTest.java
- 여기에 내용 기재
- 회원가입시 password 와 passwordCheck 를 통해 두 패스워드가 같은지 확인하는 로직을 추가했습니다.
- 여기에 내용 기재
=> [P2P-28] 회원가입시 패스워드 확인 로직 추가

src/main/java/com/prgrms/p2p/domain/like/repository/CourseLikeRepository.java, src/main/java/com/prgrms/p2p/domain/like/service/CourseLikeService.java
- 코스 조회 로직의 의존성 해결을 위해 먼저 코스 좋아요 기능을 구현합니다.
- 기존에 작성되었던 장소 좋아요 기능과 매우 흡사합니다.
- 예전에 작성된 코드(장소 좋아요) 를 못 보신 분은 여기서 주의 깊게 봐주시면 됩니다.
=> [P2P-109] 코스 좋아요 토글 기능 추가

src/main/java/com/prgrms/p2p/domain/bookmark/entity/Bookmark.java, src/main/java/com/prgrms/p2p/domain/bookmark/entity/CourseBookmark.java, src/main/java/com/prgrms/p2p/domain/bookmark/repository/CourseBookmarkRepository.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/BookmarkPolicy.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/CourseBookmarkService.java
- 코스 상세 조회시 필요한 북마크 정보로 인하여 먼저 개발을 시작합니다.
- 코스 좋아요와 마찬가지로 기능이 동작합니다.
- 코스 좋아요랑 똑같이 생겨서 라이트하게 읽어보시면 좋을 듯!
=> [P2P-105] 코스 북마크 추가/삭제 기능을 추가합니다.

src/main/java/com/prgrms/p2p/domain/course/entity/CoursePlace.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseService.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-1] fix: 생성자 "}" 누락, 필요없는 메서드 삭제, queryDsl 생성자 수정

src/main/java/com/prgrms/p2p/domain/bookmark/entity/PlaceBookmark.java, src/main/java/com/prgrms/p2p/domain/bookmark/repository/PlaceBookmarkRepository.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/CourseBookmarkService.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/PlaceBookmarkService.java
- 장소 조회시 필요한 북마크 정보로 인하여 먼저 개발을 시작합니다.
- 장소 좋아요와 동일하게 기능이 동작합니다.
- 장소 좋아요랑 똑같이 생겨서 라이트하게 읽어보시면 좋을 듯!
=> [P2P-103] 장소 북마크 추가/삭제 기능을 추가합니다.

src/main/java/com/prgrms/p2p/domain/course/entity/Course.java, src/main/java/com/prgrms/p2p/domain/course/entity/CoursePlace.java, src/main/java/com/prgrms/p2p/domain/place/controller/PlaceController.java, src/main/java/com/prgrms/p2p/domain/place/dto/DetailPlaceResponse.java, src/main/java/com/prgrms/p2p/domain/place/dto/SummaryPlaceResponse.java, src/main/java/com/prgrms/p2p/domain/place/entity/Place.java, src/main/java/com/prgrms/p2p/domain/place/repository/PlaceSearchRepository.java, src/main/java/com/prgrms/p2p/domain/place/repository/PlaceSearchRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/place/service/PlaceService.java, src/main/java/com/prgrms/p2p/domain/place/util/PlaceConverter.java, src/main/java/com/prgrms/p2p/domain/user/entity/User.java, src/test/java/com/prgrms/p2p/domain/place/service/PlaceServiceTest.java
…반환 로직 추가
- 여기에 내용 기재
> 유저 정보 있을 시 ?
세부 조회 = 북마크, 좋아요 여부
간단 목록 조회 = 북마크 여부
를 반환합니다.
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-54] 장소 상세조회 - 북마크, 좋아요 정보 반환 추가

src/test/java/com/prgrms/p2p/domain/like/entity/CourseLikeTest.java, src/test/java/com/prgrms/p2p/domain/like/entity/PlaceLikeTest.java, src/test/java/com/prgrms/p2p/domain/like/repository/PlaceLikeRepositoryTest.java, src/test/java/com/prgrms/p2p/domain/like/service/CourseLikeServiceTest.java, src/test/java/com/prgrms/p2p/domain/like/service/PlaceLikeServiceTest.java
- 코스와 장소 객체의 필드 정보 변경으로 인하여 테스트 코드를 수정합니다.
- spot과 category 객체를 수정합니다.
- 따로없음
=> [P2P-106] 객체 생성 로직 변경으로 인한 테스트 코드 수정

src/main/java/com/prgrms/p2p/domain/course/dto/CreateCourseRequest.java, src/main/java/com/prgrms/p2p/domain/course/dto/DetailCourseResponse.java, src/main/java/com/prgrms/p2p/domain/course/dto/SearchCourseRequest.java, src/main/java/com/prgrms/p2p/domain/course/dto/SummaryCourseResponse.java, src/test/java/com/prgrms/p2p/domain/place/entity/PlaceTest.java, src/test/java/com/prgrms/p2p/domain/place/service/PlaceServiceTest.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-30] Builder.Default 이슈 및 enum 내부 변경에 따른 변경

src/main/java/com/prgrms/p2p/domain/course/entity/Course.java
- Course 생성자 생성
- Course 생성자 생성
- 여기에 내용 기재
=> [P2P-41] Course 생성자 생성

src/main/java/com/prgrms/p2p/domain/course/dto/DetailCourseResponse.java, src/main/java/com/prgrms/p2p/domain/course/entity/Theme.java, src/test/java/com/prgrms/p2p/domain/course/entity/CourseTest.java, src/test/java/com/prgrms/p2p/domain/like/entity/CourseLikeTest.java, src/test/java/com/prgrms/p2p/domain/like/entity/PlaceLikeTest.java, src/test/java/com/prgrms/p2p/domain/like/service/CourseLikeServiceTest.java, src/test/java/com/prgrms/p2p/domain/place/service/PlaceServiceTest.java, src/test/java/com/prgrms/p2p/domain/user/entity/UserTest.java
- Theme 추가
- Theme 추가
- 여기에 내용 기재
=> [P2P-41] Theme 추가

src/main/java/com/prgrms/p2p/domain/user/controller/UserController.java, src/main/java/com/prgrms/p2p/domain/user/dto/ModifyRequest.java, src/main/java/com/prgrms/p2p/domain/user/service/UserService.java
- 여기에 내용 기재
- 유저 정보 Controller단과 서비스에서 추가했습니다.
- 로그인이 된지 아닌지는 범석님 작업 끝나고 위에 한번에 다 붙이기로 계획중입니다.
- 여기에 내용 기재
=> [P2P-26] 유저 정보 수정

src/main/java/com/prgrms/p2p/domain/user/controller/UserController.java, src/main/java/com/prgrms/p2p/domain/user/dto/ChangePasswordRequest.java, src/main/java/com/prgrms/p2p/domain/user/service/UserService.java
- 여기에 내용 기재
- 유저가 자신의 비밀번호 수정, 이것도 id를 가져오지않아서 범석님 작업끝나고 일괄 추가 하겠습니다.
- 여기에 내용 기재
=> [P2P-35] 비밀번호 변경

src/main/java/com/prgrms/p2p/domain/course/util/CoursePlaceConverter.java, src/main/java/com/prgrms/p2p/domain/place/controller/PlaceController.java, src/main/java/com/prgrms/p2p/domain/place/entity/Address.java, src/main/java/com/prgrms/p2p/domain/place/entity/Category.java, src/main/java/com/prgrms/p2p/domain/place/entity/Place.java, src/main/java/com/prgrms/p2p/domain/place/repository/PlaceRepository.java, src/main/java/com/prgrms/p2p/domain/place/repository/PlaceSearchRepository.java, src/main/java/com/prgrms/p2p/domain/place/repository/PlaceSearchRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/place/service/PlaceService.java, src/test/java/com/prgrms/p2p/domain/like/entity/PlaceLikeTest.java, src/test/java/com/prgrms/p2p/domain/like/repository/PlaceLikeRepositoryTest.java, src/test/java/com/prgrms/p2p/domain/like/service/PlaceLikeServiceTest.java, src/test/java/com/prgrms/p2p/domain/place/entity/PlaceTest.java, src/test/java/com/prgrms/p2p/domain/place/service/PlaceServiceTest.java, src/test/resources/application.yaml
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-54] 유저가 북마크한 목록 조회 기능 추가 및 테스트, Place의 ImageUrl 필드의 삭제

src/main/java/com/prgrms/p2p/domain/user/controller/UserController.java, src/main/java/com/prgrms/p2p/domain/user/service/UserService.java
- 여기에 내용 기재
- 사용자 탈퇴 기능 추가, 마찬가지로 userId는 나중에 추가 할 예정
- 여기에 내용 기재
=> [P2P-51] feat: 유저 탈퇴 기능 추가

build.gradle, src/main/java/com/prgrms/p2p/domain/user/config/config/CacheConfig.java, src/main/java/com/prgrms/p2p/domain/user/config/config/InterceptorConfig.java, src/main/java/com/prgrms/p2p/domain/user/config/config/RedisRepositoryConfig.java, src/main/java/com/prgrms/p2p/domain/user/config/config/WebSecurityConfig.java, src/main/java/com/prgrms/p2p/domain/user/config/security/RedisInterceptor.java, src/main/java/com/prgrms/p2p/domain/user/config/security/RequestServletFilter.java, src/main/java/com/prgrms/p2p/domain/user/config/security/RequestServletWrapper.java, src/main/java/com/prgrms/p2p/domain/user/service/UserService.java
- 로그인시 인터셉터 부분에서 사용자가 로그인을 할 수 있는지 체크
- 로그인 api 요청시 인터셉터 처리
- 인터셉터 안에서 Redis 접근
- 인터셉테에서 RequestBody 접근했을 시 controller에서 접근 못하는 문제 해결
- 여기에 내용 기재
=> [P2P-151] 유저 로그인 관련 인터셉터 설정

src/main/java/com/prgrms/p2p/domain/course/entity/Course.java, src/main/java/com/prgrms/p2p/domain/course/entity/CoursePlace.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseRepository.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java, src/test/java/com/prgrms/p2p/domain/course/entity/CoursePlaceTest.java, src/test/java/com/prgrms/p2p/domain/course/entity/CourseTest.java, src/test/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImplTest.java
- 코스 검색 기능 테스트  
- 코스 검색 기능 테스트  
- 여기에 내용 기재
=> [P2P-42] test: 코스 검색 기능 테스트  

src/main/java/com/prgrms/p2p/domain/course/entity/Course.java, src/main/java/com/prgrms/p2p/domain/course/entity/CoursePlace.java
- refactor: Course, CoursePlace 수정
- refactor: Course, CoursePlace 수정
- 여기에 내용 기재
=> [P2P-38] refactor: Course, CoursePlace 수정

src/main/java/com/prgrms/p2p/domain/user/aop/AuthAspect.java, src/main/java/com/prgrms/p2p/domain/user/aop/CurrentUserArgumentResolver.java, src/main/java/com/prgrms/p2p/domain/user/aop/annotation/Auth.java, src/main/java/com/prgrms/p2p/domain/user/aop/annotation/CurrentUser.java, src/main/java/com/prgrms/p2p/domain/user/config/config/InterceptorConfig.java, src/main/java/com/prgrms/p2p/domain/user/config/security/JwtTokenProvider.java, src/main/java/com/prgrms/p2p/domain/user/controller/UserController.java
- 어노테이션을 이용해 로그인한 사용자를 알아내는 기능을 추가하고자 했습니다.
- AOP를 통해서 controller 수행 전에 토큰을 통해 사용자가 있는지 확인하는 로직을 추가했습니다.
- @CurrentUser : 현재 로그인한 사용자 
- @Auth : 메소드 실행전 확인하는 aop
- 여기에 내용 기재
=> [P2P-151] CurrentUser 어노테이션, Auth 어노테이션(aop) 기능 추가했습니다.

src/main/java/com/prgrms/p2p/domain/user/dto/LoginRequest.java, src/main/java/com/prgrms/p2p/domain/user/dto/LoginResponse.java, src/main/java/com/prgrms/p2p/domain/user/entity/User.java, src/main/java/com/prgrms/p2p/domain/user/util/UserConverter.java
- Postman을 이용해서 테스트를 해본결과 제대로 response가 안나와 수정했습니다.
- 로그인시 패스워드를 확인하는 과정에서 잘못된 코드가 있어 수정했습니다.
- 반환되는 response dto를 수정해 제대로 반환되도록 했습니다.
- 여기에 내용 기재
=> [P2P-20] 로그인시 반환되는 ResponseDto 수정 및 패스워드 확인 로직 수정

src/main/java/com/prgrms/p2p/domain/user/dto/SignUpRequest.java
- 여기에 내용 기재
- SignUp DTO에 NoArgsConstructor 어노테이션 추가했습니다.
- 여기에 내용 기재
=> [P2P-19] SignUp DTO에 NoArgsConstructor 어노테이션 추가

src/main/java/com/prgrms/p2p/domain/user/aop/CurrentUserArgumentResolver.java, src/main/java/com/prgrms/p2p/domain/user/config/config/InterceptorConfig.java
- 여기에 내용 기재
- 실수로 뺀 어노테이션과 잘못 적힌 Url을 수정했습니다.
- 여기에 내용 기재
=> [P2P-151] 빈 설정을 위한 @Component 어노테이션 추가 및 인터셉터에 접근하기 위한 Url 설정 수정

src/main/java/com/prgrms/p2p/domain/user/config/security/JwtAuthenticationFilter.java, src/main/java/com/prgrms/p2p/domain/user/config/security/JwtTokenProvider.java, src/main/java/com/prgrms/p2p/domain/user/entity/Authority.java, src/main/java/com/prgrms/p2p/domain/user/entity/User.java, src/main/java/com/prgrms/p2p/domain/user/pojo/CustomUserDetails.java, src/main/java/com/prgrms/p2p/domain/user/service/CustomUserDetailService.java, src/main/java/com/prgrms/p2p/domain/user/util/UserConverter.java
- 여기에 내용 기재
- Header를 통해 토큰을 가져오는 과정에서 실수 가 있어서 해결했습니다...
- 유저에 authority를 추가했습니다.
- 여기에 내용 기재
=> [P2P-20] 로그인 후 SecurityContextHolder에 authentication이 저장이 안되는 오류 해결

src/main/java/com/prgrms/p2p/domain/user/controller/UserController.java
- 여기에 내용 기재
- JSON으로 보내는데 String으로 받으니 {정보} 형태로 String에 다 담겨서 수정했습니다.
- 여기에 내용 기재
=> [P2P-46] 이메일과 닉네임 RequestBody 타입 수정

src/main/java/com/prgrms/p2p/domain/user/aop/CurrentUserArgumentResolver.java, src/main/java/com/prgrms/p2p/domain/user/controller/UserController.java, src/main/java/com/prgrms/p2p/domain/user/dto/OtherUserDetailResponse.java, src/main/java/com/prgrms/p2p/domain/user/service/UserService.java, src/main/java/com/prgrms/p2p/domain/user/util/UserConverter.java
- 자신과 타인의 정보를 볼 수 있습니다.
- 타인의 정보를 보여주는 dto 추가
- service에서 타인의 정보를 조회하는 로직 추가
- controller에 자신과 타인의 정보를 조회하는 api를 각각 추가
- **CurrentUser에서 토큰값이 없다면 Null을 반환하도록 했습니다.**
- 여기에 내용 기재
=> [P2P-22] 자신 또는 타인의 정보를 볼 수 있는 API 기능 추가

src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseRepository.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseQueryService.java
- 코스 API를 추가합니다. 
- 코스 API를 추가합니다. 
- 여기에 내용 기재
=> [P2P-37] 코스 API를 추가합니다. 

src/main/java/com/prgrms/p2p/domain/bookmark/controller/BookmarkRestController.java, src/main/java/com/prgrms/p2p/domain/bookmark/controller/BookmarkType.java, src/main/java/com/prgrms/p2p/domain/bookmark/exception/NotFoundException.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/BookmarkService.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/BookmarkServiceFactory.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/CourseBookmarkService.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/PlaceBookmarkService.java, src/main/java/com/prgrms/p2p/domain/common/dto/ErrorResponse.java, src/main/java/com/prgrms/p2p/domain/common/exception/BadRequestException.java, src/main/java/com/prgrms/p2p/domain/common/exception/ExceptionAdvice.java, src/main/java/com/prgrms/p2p/domain/common/exception/NotFoundException.java, src/main/java/com/prgrms/p2p/domain/common/exception/UnAuthorizedException.java, src/main/java/com/prgrms/p2p/domain/like/controller/LikeType.java
- 코스/장소 북마크를 API가 필요합니다.
- 코스 장소 좋아요 기능과 동일하게 구현되었습니다.
- 따로 없음
=> [P2P-152] 코스/장소 북마크를 API를 추가합니다.

src/main/java/com/prgrms/p2p/domain/user/config/security/RequestServletFilter.java, src/main/java/com/prgrms/p2p/domain/user/controller/UserController.java, src/main/java/com/prgrms/p2p/domain/user/entity/User.java, src/main/java/com/prgrms/p2p/domain/user/service/UserService.java
- 여기에 내용 기재
- request 로 multipart가 왔을 때 Multipart 로 못 읽게 된 부분 수정(인터셉터때문에 제가 설정한거 때문에 ㅠㅠ)
- 프로필사진을 수정
- 여기에 내용 기재
=> [P2P-24] 사용자가 프로필 사진을 변경할 수 있습니다.

src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/dto/CreateCourseRequest.java
- User Null 체크 변경
- User Null 체크 변경
- 여기에 내용 기재
=> [P2P-38] FIX: User Null 체크 변경

src/main/java/com/prgrms/p2p/domain/comment/dto/CourseCommentResponse.java, src/main/java/com/prgrms/p2p/domain/comment/dto/CreateCourseCommentRequest.java, src/main/java/com/prgrms/p2p/domain/comment/entity/Comment.java, src/main/java/com/prgrms/p2p/domain/comment/entity/CourseComment.java, src/main/java/com/prgrms/p2p/domain/comment/entity/PlaceComment.java, src/main/java/com/prgrms/p2p/domain/comment/repository/CourseCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/repository/PlaceCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchCourseCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchCourseCommentRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/comment/service/CourseCommentService.java, src/main/java/com/prgrms/p2p/domain/comment/util/CommentConverter.java, src/main/java/com/prgrms/p2p/domain/place/controller/PlaceController.java, src/main/java/com/prgrms/p2p/domain/place/dto/DetailPlaceResponse.java, src/main/java/com/prgrms/p2p/domain/place/dto/RecordRequest.java, src/main/java/com/prgrms/p2p/domain/place/dto/SearchPlaceRequest.java, src/main/java/com/prgrms/p2p/domain/place/dto/SummaryPlaceResponse.java, src/main/java/com/prgrms/p2p/domain/place/service/PlaceService.java, src/test/java/com/prgrms/p2p/domain/comment/repository/SearchCourseCommentRepositoryImplTest.java, src/test/java/com/prgrms/p2p/domain/comment/service/CourseCommentServiceTest.java, src/test/java/com/prgrms/p2p/domain/place/service/PlaceServiceTest.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-81] 코스 댓글 관련 기능을 추가합니다

src/main/java/com/prgrms/p2p/domain/user/controller/UserController.java, src/main/java/com/prgrms/p2p/domain/user/dto/ChangePasswordRequest.java, src/main/java/com/prgrms/p2p/domain/user/dto/ModifyRequest.java, src/main/java/com/prgrms/p2p/domain/user/entity/User.java, src/main/java/com/prgrms/p2p/domain/user/service/UserService.java
- 여기에 내용 기재
- 잘못된 코드들 수정 하고 
- 없는 어노테이션을 추가했습니다.
- 여기에 내용 기재
=> [P2P-26] 회원 정보 수정 로직 수정

src/main/java/com/prgrms/p2p/domain/comment/repository/CourseCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchCourseCommentRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/comment/service/CourseCommentService.java, src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/user/controller/UserController.java, src/main/java/com/prgrms/p2p/domain/user/entity/User.java, src/main/java/com/prgrms/p2p/domain/user/service/UserService.java, src/main/java/com/prgrms/p2p/domain/user/util/Validation.java, src/test/java/com/prgrms/p2p/domain/comment/repository/SearchCourseCommentRepositoryImplTest.java, src/test/java/com/prgrms/p2p/domain/comment/service/CourseCommentServiceTest.java, src/test/java/com/prgrms/p2p/domain/place/service/PlaceServiceTest.java, src/test/java/com/prgrms/p2p/domain/user/util/ValidationTest.java
- 여기에 내용 기재
- 비밀번호, 닉네임 정규표현식 수정했습니다.
- 여기에 내용 기재
=> [P2P-26] 비밀번호, 닉네임 검증 정규표현식 수정 및 안되는 코드 주석처리

src/main/java/com/prgrms/p2p/domain/user/config/config/InterceptorConfig.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-26] feat: CORS 설정 ~!!!

src/main/java/com/prgrms/p2p/domain/place/entity/PhoneNumber.java, src/main/java/com/prgrms/p2p/domain/user/entity/User.java, src/main/java/com/prgrms/p2p/domain/user/service/UserService.java, src/test/java/com/prgrms/p2p/domain/user/service/UserServiceTest.java
- 여기에 내용 기재
- 유저 서비스 로그인을 제외한 테스트 코드 추가(아직 Mock 찾는중), PhoneNumber 정규식 필드 삭제, 유저에서 사용하지 않는 @Builder 삭제 
- 여기에 내용 기재
=> [P2P-23] [P2P-27,36,52] 유저 테스트 추가 

src/main/java/com/prgrms/p2p/domain/bookmark/service/CourseBookmarkService.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/PlaceBookmarkService.java, src/main/java/com/prgrms/p2p/domain/common/controller/CommonController.java, src/main/java/com/prgrms/p2p/domain/user/entity/User.java, src/main/java/com/prgrms/p2p/domain/user/service/UserService.java, src/test/java/com/prgrms/p2p/domain/bookmark/service/CourseBookmarkServiceTest.java, src/test/java/com/prgrms/p2p/domain/bookmark/service/PlaceBookmarkServiceTest.java
- 북마크 서비스에 대한 검증 테스트가 필요합니다.
- User에서 발생하는 오류를 수정하고
- 없음
=> [P2P-155] 북마크 테스트를 추가합니다.

src/main/java/com/prgrms/p2p/domain/comment/repository/CourseCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchCourseCommentRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/comment/service/CourseCommentService.java, src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/dto/CoursePlaceResponse.java, src/main/java/com/prgrms/p2p/domain/course/dto/SearchCourseRequest.java, src/main/java/com/prgrms/p2p/domain/course/dto/SummaryCourseResponse.java, src/main/java/com/prgrms/p2p/domain/course/entity/Region.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/course/util/CourseConverter.java, src/main/java/com/prgrms/p2p/domain/course/util/CoursePlaceConverter.java
- 여기에 내용 기재
- 코스 목록 조회 기능 수정 및 추가했습니다.
- 여기에 내용 기재
=> [P2P-41] 코스 목록 조회 기능 수정

src/main/java/com/prgrms/p2p/domain/bookmark/entity/Bookmark.java, src/main/java/com/prgrms/p2p/domain/bookmark/entity/CourseBookmark.java, src/main/java/com/prgrms/p2p/domain/bookmark/entity/PlaceBookmark.java, src/main/java/com/prgrms/p2p/domain/bookmark/repository/CourseBookmarkRepository.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/BookmarkServiceFactory.java, src/main/java/com/prgrms/p2p/domain/like/entity/CourseLike.java, src/main/java/com/prgrms/p2p/domain/like/entity/Like.java, src/main/java/com/prgrms/p2p/domain/like/entity/PlaceLike.java, src/main/java/com/prgrms/p2p/domain/like/service/CourseLikeService.java, src/main/java/com/prgrms/p2p/domain/like/service/LikeServiceFactory.java, src/main/java/com/prgrms/p2p/domain/like/service/PlaceLikeService.java, src/test/java/com/prgrms/p2p/domain/bookmark/entity/CourseBookmarkTest.java, src/test/java/com/prgrms/p2p/domain/bookmark/entity/PlaceBookmarkTest.java, src/test/java/com/prgrms/p2p/domain/bookmark/repository/PlaceBookmarkRepositoryTest.java, src/test/java/com/prgrms/p2p/domain/bookmark/service/BookmarkServiceFactoryTest.java, src/test/java/com/prgrms/p2p/domain/bookmark/service/CourseBookmarkServiceTest.java, src/test/java/com/prgrms/p2p/domain/bookmark/service/PlaceBookmarkServiceTest.java, src/test/java/com/prgrms/p2p/domain/like/entity/CourseLikeTest.java, src/test/java/com/prgrms/p2p/domain/like/entity/PlaceLikeTest.java, src/test/java/com/prgrms/p2p/domain/like/service/CourseLikeServiceTest.java, src/test/java/com/prgrms/p2p/domain/like/service/LikeServiceFactoryTest.java, src/test/java/com/prgrms/p2p/domain/like/service/PlaceLikeServiceTest.java
- 북마크와 좋아요 엔티티와 레포지토리에 대한 검증 테스트가 필요합니다.
- 스프링 컨테이너에서 서비스를 가지고 오는 로직 검증도 추가하였습니다.
=> [P2P-157] 북마크, 좋아요 엔티티, 레포지토리 테스트 추가

src/main/java/com/prgrms/p2p/domain/course/dto/SummaryCourseResponse.java, src/main/java/com/prgrms/p2p/domain/course/util/CourseConverter.java
- user 프로필 url가 누락돼서 추가합니다,,
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-41] user 프로필 url 추가

src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/dto/SearchCourseRequest.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java, src/test/java/com/prgrms/p2p/domain/place/service/PlaceServiceTest.java
- 여기에 내용 기재
- 상기 기능을 추가하고 요청 dto에 관련 필드(placeId)가 추가되었습니다.
- 여기에 내용 기재
=> [P2P-165] 코스 검색에 특정 장소가 검색 조건에 추가되었습니다.

src/main/java/com/prgrms/p2p/domain/user/config/config/InterceptorConfig.java, src/main/java/com/prgrms/p2p/domain/user/config/security/RedisInterceptor.java, src/main/java/com/prgrms/p2p/domain/user/controller/UserController.java, src/main/java/com/prgrms/p2p/domain/user/dto/ChangeProfileResponse.java, src/main/java/com/prgrms/p2p/domain/user/dto/SignUpResponse.java, src/main/java/com/prgrms/p2p/domain/user/service/UserService.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-20] 유저 로그인, 프로필 수정 api 반환값 수정, cors 관련 인터셉터 부분 로직 수정했습니다.

src/main/java/com/prgrms/p2p/domain/user/controller/UserController.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-20] refactor: @CrossOrigin 을 유저 컨트롤러에 추가했습니다.

src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/dto/DetailCourseResponse.java, src/main/java/com/prgrms/p2p/domain/course/util/CourseConverter.java
- 코스 상세 조회 수정
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-41] 코스 상세 조회 수정

src/main/java/com/prgrms/p2p/domain/comment/dto/CreateCourseCommentRequest.java, src/main/java/com/prgrms/p2p/domain/comment/repository/CourseCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/service/CourseCommentService.java, src/main/java/com/prgrms/p2p/domain/comment/util/CommentConverter.java, src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseRepository.java, src/main/java/com/prgrms/p2p/domain/course/service/CoursePlaceService.java, src/test/java/com/prgrms/p2p/domain/comment/repository/SearchCourseCommentRepositoryImplTest.java, src/test/java/com/prgrms/p2p/domain/comment/service/CourseCommentServiceTest.java, src/test/java/com/prgrms/p2p/domain/place/service/PlaceServiceTest.java
- dto Optional 처리하던걸 null로 바꾸면서 관련 로직 변경했습니다.
- 일부 쿼리문 정상동작 안하는거 삭제했습니다.
- 어노테이션 잘못 작성한 부분에 대해 @Param으로 수정했습니다.
- Dto로 받는거 test로 수정안한 부분에 대해 수정했습니다.
- 여기에 내용 기재
=> [P2P-169] placeService, courseComment 관련 test 빌드 깨짐 이슈 해결입니다.

src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java
- 처음에 확정 조건으로 조회하는걸로 짜서 조건부로 바뀌었을때 미처 반영못하고 누락된 부분이 있었네요..ㅜ 죄송합네다.
- 여기에 내용 기재
=> [P2P-161] course의 placeId 조회에 BooleanExpression이 누락된 것을 적용했습니다.

build.gradle, src/main/java/com/prgrms/p2p/domain/user/controller/UserController.java, src/main/java/com/prgrms/p2p/domain/user/dto/ChangePasswordRequest.java, src/main/java/com/prgrms/p2p/domain/user/dto/ChangeProfileResponse.java, src/main/java/com/prgrms/p2p/domain/user/dto/LoginFailResponse.java, src/main/java/com/prgrms/p2p/domain/user/dto/LoginRequest.java, src/main/java/com/prgrms/p2p/domain/user/dto/LoginResponse.java, src/main/java/com/prgrms/p2p/domain/user/dto/ModifyRequest.java, src/main/java/com/prgrms/p2p/domain/user/dto/OtherUserDetailResponse.java, src/main/java/com/prgrms/p2p/domain/user/dto/SignUpRequest.java, src/main/java/com/prgrms/p2p/domain/user/dto/SignUpResponse.java, src/main/java/com/prgrms/p2p/domain/user/dto/UserDetailResponse.java, src/main/java/com/prgrms/p2p/domain/user/pojo/CustomUserDetails.java
- [P2P-99] 스웨거를 추가합니다. (지라 이슈)
- 스웨거 관련 dependency를 gradle에 추가했습니다.
- dto와 controller에 스웨거 설정을 했습니다.
- 로그인 실패시 response dto가 없어서 추가했습니다.
- 여기에 내용 기재
=> [P2P-99] 스웨거 설정을 위한 의존성 추가 및 유저 컨트롤러에 스웨거 설정을 했습니다.

src/main/java/com/prgrms/p2p/domain/user/pojo/CustomUserDetails.java
- 여기에 내용 기재
- 잘못된 어노테이션을 사용해서 수정했습니다.
- 여기에 내용 기재
=> [P2P-99] CustomUserDetails  설정 수정

src/test/java/com/prgrms/p2p/domain/user/service/UserServiceTest.java
- 여기에 내용 기재
- 프로필 사진 추가 및 전에 작성했던 테스트 수정했습니다
- 여기에 내용 기재
=> [P2P-25] [P2P-27,36]  유저 테스트 추가 및 변경

src/main/java/com/prgrms/p2p/domain/course/dto/CreateCourseRequest.java, src/main/java/com/prgrms/p2p/domain/course/dto/SummaryCourseResponse.java, src/main/java/com/prgrms/p2p/domain/course/entity/Course.java, src/main/java/com/prgrms/p2p/domain/course/util/CourseConverter.java
- SummaryCourseResponse 수정
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-41] SummaryCourseResponse 수정

src/main/java/com/prgrms/p2p/domain/course/dto/CoursePlaceResponse.java, src/main/java/com/prgrms/p2p/domain/course/dto/CreateCoursePlaceRequest.java, src/main/java/com/prgrms/p2p/domain/course/dto/DetailCourseResponse.java, src/main/java/com/prgrms/p2p/domain/course/dto/SummaryCourseResponse.java, src/main/java/com/prgrms/p2p/domain/course/entity/CoursePlace.java, src/main/java/com/prgrms/p2p/domain/course/util/CourseConverter.java, src/main/java/com/prgrms/p2p/domain/course/util/CoursePlaceConverter.java, src/test/java/com/prgrms/p2p/domain/course/entity/CoursePlaceTest.java, src/test/java/com/prgrms/p2p/domain/course/entity/CourseTest.java, src/test/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImplTest.java
- course 필드 변경 및 썸네일 로직 추가
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173] course 필드 변경 및 썸네일 로직 추가

src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/dto/SearchCourseRequest.java, src/main/java/com/prgrms/p2p/domain/course/entity/Course.java, src/main/java/com/prgrms/p2p/domain/course/entity/Sorting.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java
- 코스 정렬 조건을 추가합니다
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173] 코스 정렬 조건을 추가합니다

src/main/java/com/prgrms/p2p/domain/user/dto/ChangeProfileResponse.java
- 여기에 내용 기재
- Response body에 들어가는 url 을 profileImage로 변경했습니다.
- 여기에 내용 기재
=> [P2P-24] 기존 profileurl을 반환하던 것을 profileImage로 변경했습니다.

src/main/java/com/prgrms/p2p/domain/user/service/UserService.java
- 여기에 내용 기재
- 인코딩된 비밀번호를 넣어줘야 하는데 그냥 비밀번호를 넣어서 수정했습니다.
- 여기에 내용 기재
=> [P2P-35] 비밀번호 변경시 로직을 수정했습니다.

src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/entity/Period.java, src/main/java/com/prgrms/p2p/domain/course/util/CourseConverter.java
- JsonCreator가 안 먹는 에러 수정
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173] 코스 Period 에러 수정

src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java
- placeId로 검색 시 장소 정보가 모두 제공되지 않는 오류 해결
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173] placeId로 검색 시 장소 정보가 모두 제공되지 않는 오류 해결

src/main/java/com/prgrms/p2p/domain/bookmark/repository/CourseBookmarkRepository.java, src/main/java/com/prgrms/p2p/domain/bookmark/repository/PlaceBookmarkRepository.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/BookmarkService.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/CourseBookmarkService.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/PlaceBookmarkService.java, src/main/java/com/prgrms/p2p/domain/comment/repository/CourseCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/service/CourseCommentService.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseRepository.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseService.java, src/main/java/com/prgrms/p2p/domain/like/repository/CourseLikeRepository.java, src/main/java/com/prgrms/p2p/domain/like/repository/PlaceLikeRepository.java, src/main/java/com/prgrms/p2p/domain/like/service/CourseLikeService.java, src/main/java/com/prgrms/p2p/domain/like/service/LikeService.java, src/main/java/com/prgrms/p2p/domain/like/service/PlaceLikeService.java, src/main/java/com/prgrms/p2p/domain/user/dto/OtherUserDetailResponse.java, src/main/java/com/prgrms/p2p/domain/user/dto/UserBookmarkResponse.java, src/main/java/com/prgrms/p2p/domain/user/dto/UserCommentResponse.java, src/main/java/com/prgrms/p2p/domain/user/dto/UserCounts.java, src/main/java/com/prgrms/p2p/domain/user/dto/UserDetailResponse.java, src/main/java/com/prgrms/p2p/domain/user/dto/UserLikeResponse.java, src/main/java/com/prgrms/p2p/domain/user/service/UserFacadeService.java, src/main/java/com/prgrms/p2p/domain/user/service/UserService.java, src/main/java/com/prgrms/p2p/domain/user/util/UserConverter.java
- 프론트팀의 요청!
- 유저 정보조회를 할 때 유저의 북마크, 좋아요, 코스 , 댓글 의 수를 보여줍니다.
-  좋아요, 코스, 댓글, 북마크의 레포지토리와 서비스 단을 조금 수정했습니다.
- 문제가 없는지 봐주시면 감사하겠습니다.
=> [P2P-22] 유저 정보 조회시 유저의 북마크, 좋아요, 등록한 코스, 댓글 개수를 보여줍니다.

src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/dto/CreateCoursePlaceRequest.java, src/main/java/com/prgrms/p2p/domain/course/entity/CoursePlace.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java
- 코스 기본 페이징 설정 및 Boolean 기본 값 추가
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173] 코스 기본 페이징 설정 및 Boolean 기본 값 추가

src/main/java/com/prgrms/p2p/domain/user/config/security/RequestServletWrapper.java
- 여기에 내용 기재
- request를 wrapper 하던 부분을 수정했습니다.
- 여기에 내용 기재
=> [P2P-151] request Body 에 한글을 넣을 수 있습니다.

src/main/java/com/prgrms/p2p/domain/user/service/UserService.java
- 여기에 내용 기재
- 이미 저장되어 있는 비밀번호와 바꿀 비밀번호가 같은 경우를 체크해 예외를 던져 줍니다.
- 여기에 내용 기재
=> [P2P-35] 비밀번호 변경시 확인하는 로직 추가

src/test/java/com/prgrms/p2p/domain/user/service/UserServiceTest.java
- 여기에 내용 기재
- 각자 상황에 맞는 예외를 넣어 주었습니다.
- 실패 케이스 추가(이미 저장된 비밀번호와 변경하려는 비밀번호가 같은 경우)
- 여기에 내용 기재
=> [P2P-36] 패스워드 변경 테스트 예외 처리 수정 및 테스트 케이스 추가

src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/dto/CreateCoursePlaceRequest.java, src/main/java/com/prgrms/p2p/domain/place/entity/Category.java
- 기본 카테고리 생성
- 기본 카테고리 생성
- 여기에 내용 기재
=> [P2P-173] 기본 카테고리 생성

src/test/java/com/prgrms/p2p/domain/user/service/UserServiceTest.java, src/test/resources/application.yaml
- 여기에 내용 기재
- 여러가지 방법을 시도 해봤으나(@DataRedisTest ,embedded redis, redismock) 계속 연결실패로 떠서 임시 방편으로 test파일에 현재 Redis 서버주소를 넣었더니 코드가 정상적으로 실행되어 일단은 올리기로 했습니다.. 죄송합니다 (yaml파일에는 localhost로 표기했습니다.)
- 여기에 내용 기재
=> [P2P-21] 유저 로그인 테스트 코드 추가

src/test/java/com/prgrms/p2p/domain/user/util/ValidationTest.java
- 여기에 내용 기재
- 닉네임에 이제 한글을 넣을 수 있습니다.
- 여기에 내용 기재
=> [P2P-140] Nickname 테스트 코드 추가했습니다.

src/main/java/com/prgrms/p2p/domain/comment/repository/CourseCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/service/CourseCommentService.java, src/main/java/com/prgrms/p2p/domain/course/dto/CreateCoursePlaceRequest.java, src/main/java/com/prgrms/p2p/domain/course/util/CoursePlaceConverter.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173] 충돌 해결

src/test/java/com/prgrms/p2p/domain/user/service/UserServiceTest.java
- 여기에 내용 기재
- 잘못된 예외를 수정
- 여기에 내용 기재
=> [P2P-23] 유저 상세조회 테스트 예외 수정

src/test/java/com/prgrms/p2p/domain/user/service/UserServiceTest.java
- 여기에 내용 기재
- 예외를 바꿨습니다.
- 여기에 내용 기재
=> [P2P-29] 유저 회원가입 테스트 예외 수정

src/test/java/com/prgrms/p2p/domain/comment/repository/SearchCourseCommentRepositoryImplTest.java, src/test/java/com/prgrms/p2p/domain/comment/service/CourseCommentServiceTest.java, src/test/java/com/prgrms/p2p/domain/comment/service/SearchCourseCommentServiceTest.java, src/test/java/com/prgrms/p2p/domain/course/entity/CoursePlaceTest.java, src/test/java/com/prgrms/p2p/domain/place/service/PlaceServiceTest.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-178] 사라졌던 테스트 복구 및 코스 상세설명 삭제를 테스트에 적용합니다

src/test/java/com/prgrms/p2p/domain/user/service/UserServiceTest.java
- 여기에 내용 기재
- 예외를 수정했습니다.
- 여기에 내용 기재
=> [P2P-52] 회원탈퇴 테스트 예외 수정

src/main/java/com/prgrms/p2p/domain/bookmark/controller/BookmarkRestController.java, src/main/java/com/prgrms/p2p/domain/bookmark/controller/BookmarkType.java, src/main/java/com/prgrms/p2p/domain/bookmark/dto/BookmarkResponse.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/BookmarkService.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/CourseBookmarkService.java, src/main/java/com/prgrms/p2p/domain/bookmark/service/PlaceBookmarkService.java, src/main/java/com/prgrms/p2p/domain/like/controller/LikeRestController.java, src/main/java/com/prgrms/p2p/domain/like/controller/LikeType.java, src/main/java/com/prgrms/p2p/domain/like/dto/LikeResponse.java, src/main/java/com/prgrms/p2p/domain/like/service/CourseLikeService.java, src/main/java/com/prgrms/p2p/domain/like/service/LikeService.java, src/main/java/com/prgrms/p2p/domain/like/service/PlaceLikeService.java
- 프론트의 요청으로 반환값을 추가해야 합니다.
- 기존 API에 반환값만 변경합니다.
=> [P2P-168] 좋아요/북마크 반환값 추가

src/main/java/com/prgrms/p2p/domain/user/entity/User.java, src/test/java/com/prgrms/p2p/domain/user/service/UserServiceTest.java
- 여기에 내용 기재
- 예외 수정
- 이메일, 닉네임 등 널값이 들어온 경우 예외를 수정
- 여기에 내용 기재
=> [P2P-27] 회원 정보 수정 테스트 코드 예외를 수정했습니다.

src/test/java/com/prgrms/p2p/domain/user/service/UserServiceTest.java
- 여기에 내용 기재
- 예외 수정
- 여기에 내용 기재
=> [P2P-21] 로그인 테스트 예외 수정했습니다.

src/main/java/com/prgrms/p2p/domain/course/service/CoursePlaceService.java, src/main/java/com/prgrms/p2p/domain/place/controller/PlaceController.java, src/main/java/com/prgrms/p2p/domain/place/service/PlaceService.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-64] 사용자 장소 등록 API 를 추가했습니다.

src/main/java/com/prgrms/p2p/domain/bookmark/controller/BookmarkRestController.java, src/main/java/com/prgrms/p2p/domain/like/controller/LikeRestController.java
- 좋아요와 북마크를 위한 swagger를 추가합니다.
- 간단하게 추가하였습니다.
=> [P2P-130] 간단한 swagger 추가

src/main/java/com/prgrms/p2p/domain/comment/repository/CourseCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchCourseCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchCourseCommentRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/comment/service/CourseCommentService.java, src/main/java/com/prgrms/p2p/domain/comment/service/SearchCourseCommentService.java, src/main/java/com/prgrms/p2p/domain/user/service/UserFacadeService.java
… Visibility.True 조건을 추가합니다.
그 외 메서드의 위치 변경(CourseCommentService -> SearchCourseCommentService)
- 삭제된 댓글까지 포함된 개수 조회하는 로직에서 살아있는 댓글 개수만 조회하도록 변경
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-22] countByUserId에 where Visibility = true 조건을 추가했습니다.

src/main/java/com/prgrms/p2p/domain/course/dto/CreateCourseRequest.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-000] 검색조건변경

src/main/java/com/prgrms/p2p/domain/course/dto/CoursePlaceResponse.java, src/main/java/com/prgrms/p2p/domain/course/dto/CreateCoursePlaceRequest.java, src/main/java/com/prgrms/p2p/domain/course/dto/UpdateCoursePlaceRequest.java, src/main/java/com/prgrms/p2p/domain/course/dto/UpdateCourseRequest.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/course/service/CoursePlaceService.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseService.java, src/main/java/com/prgrms/p2p/domain/course/util/CoursePlaceConverter.java, src/main/java/com/prgrms/p2p/domain/place/service/PlaceService.java
- 코스 수정 미완
- and 조건으로 변경
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-39] 코스 수정 미완

src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/dto/CoursePlaceRequest.java, src/main/java/com/prgrms/p2p/domain/course/dto/CreateCourseRequest.java, src/main/java/com/prgrms/p2p/domain/course/dto/SummaryCourseResponse.java, src/main/java/com/prgrms/p2p/domain/course/dto/UpdateCoursePlaceRequest.java, src/main/java/com/prgrms/p2p/domain/course/entity/Course.java, src/main/java/com/prgrms/p2p/domain/course/entity/CoursePlace.java, src/main/java/com/prgrms/p2p/domain/course/service/CoursePlaceService.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseQueryService.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseService.java, src/main/java/com/prgrms/p2p/domain/course/util/CoursePlaceConverter.java, src/main/java/com/prgrms/p2p/domain/place/controller/PlaceController.java, src/main/java/com/prgrms/p2p/domain/place/service/PlaceService.java, src/test/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImplTest.java, src/test/java/com/prgrms/p2p/domain/place/service/PlaceServiceTest.java
- 코스 수정
- 충돌 해결
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-39] 코스 수정

src/main/java/com/prgrms/p2p/domain/user/controller/UserController.java, src/main/java/com/prgrms/p2p/domain/user/dto/OtherUserDetailResponse.java, src/main/java/com/prgrms/p2p/domain/user/util/UserConverter.java
- 여기에 내용 기재
- 타인의 상세 정보를 조회하면 이메일의 정보도 보여줍니다.
- 여기에 내용 기재
=> [P2P-22] 타인의 정보 조회시 이메일 내용도 추가

src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseQueryService.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseService.java
- 코스 삭제 수정
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-60] 코스 삭제 수정

src/main/java/com/prgrms/p2p/domain/comment/controller/PlaceCommentController.java, src/main/java/com/prgrms/p2p/domain/comment/dto/PlaceCommentDto.java, src/main/java/com/prgrms/p2p/domain/comment/dto/PlaceCommentForQueryDsl.java, src/main/java/com/prgrms/p2p/domain/comment/dto/PlaceCommentResponse.java, src/main/java/com/prgrms/p2p/domain/comment/entity/PlaceComment.java, src/main/java/com/prgrms/p2p/domain/comment/repository/PlaceCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchPlaceCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchPlaceCommentRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/comment/service/PlaceCommentService.java, src/main/java/com/prgrms/p2p/domain/comment/service/SearchPlaceCommentService.java, src/main/java/com/prgrms/p2p/domain/comment/util/CommentConverter.java
- 여기에 내용 기재
-장소 댓글에 대한 등록, 수정, 삭제, 댓글리스트 가져오기 기능 추가
- 테스트는 추후 추가 예정
- 전체적으로 찰리가 했던 내용과 흡사해서 참고했습니다
- 여기에 내용 기재
=> [P2P-86] [P2P-87,90, 93]장소 댓글에 대한 등록, 수정, 삭제, 댓글 리스트 가져오기

src/main/java/com/prgrms/p2p/domain/place/controller/PlaceController.java, src/main/java/com/prgrms/p2p/domain/place/dto/SearchPlaceDto.java, src/main/java/com/prgrms/p2p/domain/place/entity/Place.java, src/main/java/com/prgrms/p2p/domain/place/repository/PlaceSearchRepository.java, src/main/java/com/prgrms/p2p/domain/place/repository/PlaceSearchRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/place/service/PlaceService.java, src/main/java/com/prgrms/p2p/domain/place/util/PlaceConverter.java, src/test/java/com/prgrms/p2p/domain/place/entity/PlaceTest.java, src/test/java/com/prgrms/p2p/domain/place/repository/PlaceSearchRepositoryTest.java, src/test/java/com/prgrms/p2p/domain/place/service/PlaceServiceTest.java
- 여기에 내용 기재
- 장소 kakaoMapId = null 이어도 등록할 수 있습니다.
- 목록 조회에서 kakaoMapId = null 인 경우 조회되지 않습니다.
- 지역별 장소 검색 기능이 추가되었습니다. (장소를 사용하는 코스의 지역을 참조하여)
- 여기에 내용 기재
=> [P2P-66] 장소 검색 조건(지역별, 카카오 맵 아이디가 존재하는 경우에만)을 추가합니다.

src/main/java/com/prgrms/p2p/domain/course/entity/Course.java, src/main/java/com/prgrms/p2p/domain/course/entity/CoursePlace.java, src/main/java/com/prgrms/p2p/domain/course/exception/LessThanZeroBadRequestException.java, src/main/java/com/prgrms/p2p/domain/course/exception/LessThanZeroSeqBadRequestException.java, src/main/java/com/prgrms/p2p/domain/course/service/CoursePlaceService.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseQueryService.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseService.java, src/main/java/com/prgrms/p2p/domain/user/service/UserFacadeService.java
- 코스 예외 추가
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-179] 코스 예외 추가

src/main/java/com/prgrms/p2p/domain/user/service/UserService.java
- 여기에 내용 기재
- 어제 저녁에 동일한 닉네임으로 변경시도시 .ifPresent 행에서 걸려서 예외처리가 되었는데 해결해달라고 요청이 와서 수정함
- 요청 내용
현재 유저 정보 수정 api(PUT - /users) 에서 닉네임을 바꾸지 않고 요청을 보냈을 때 에러를 출력하고 있습니당. 아마 중복된 닉네임을 체크해주신 부분이라고 예상하고 있는데… 인증부분은 토큰으로 확인을 하고 있으니 이 로직을 빼주셔도 될 것 같습니다.
- 여기에 내용 기재
=> [P2P-182] 그루님 요청: 동일한 닉네임으로 수정 가능

src/main/java/com/prgrms/p2p/domain/comment/service/PlaceCommentService.java, src/test/java/com/prgrms/p2p/domain/comment/service/PlaceCommentServiceTest.java
- 여기에 내용 기재
- 찰리의 수정 pr과 동일하게 장소 댓글에도 적용했습니다만 아직 Repository 테스트단은 만들고 있어서 포함되지 않았습니다.
- 여기에 내용 기재
=> [P2P-115] 장소 대댓글 관련 오류 fix(대댓글의 대댓글 작성 금지, 댓글 삭제 로직 오류)

src/main/java/com/prgrms/p2p/domain/common/exception/ExceptionAdvice.java, src/main/java/com/prgrms/p2p/domain/course/service/CoursePlaceService.java, src/test/java/com/prgrms/p2p/domain/course/entity/CoursePlaceTest.java, src/test/java/com/prgrms/p2p/domain/course/entity/CourseTest.java, src/test/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImplTest.java, src/test/java/com/prgrms/p2p/domain/course/service/CourseQueryServiceTest.java
- 테스트 및 코스 수정
- 부득이하게 courseplaceservice에서 삼항연산자를 썼는데 더 좋은 아이디어가 있으시다면 알려주세요!!
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-61] 테스트 및 코스 수정

src/main/java/com/prgrms/p2p/domain/user/service/UserService.java
- 여기에 내용 기재
- 암호화를 안하고 디비에 저장을 했던 부분을 바꿨습니다.
- 여기에 내용 기재
=> [P2P-35] 비밀번호 변경시 로그인이 안되는 문제 해결

src/main/java/com/prgrms/p2p/domain/comment/controller/MergeCommentController.java, src/main/java/com/prgrms/p2p/domain/comment/dto/CourseCommentForQueryDsl.java, src/main/java/com/prgrms/p2p/domain/comment/dto/MergeCommentResponse.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchCourseCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchCourseCommentRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchPlaceCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchPlaceCommentRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/comment/service/MergeCommentService.java, src/main/java/com/prgrms/p2p/domain/comment/util/CommentConverter.java, src/main/java/com/prgrms/p2p/domain/place/controller/PlaceController.java, src/main/java/com/prgrms/p2p/domain/user/config/config/WebSecurityConfig.java, src/test/java/com/prgrms/p2p/domain/comment/repository/SearchTotalCommentRepositoryTest.java, src/test/java/com/prgrms/p2p/domain/comment/service/MergeCommentServiceTest.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-101] 특정 사용자별로 작성된 댓글들의 목록 조회 기능 및 테스트 추가

src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseRepository.java, src/test/java/com/prgrms/p2p/domain/course/entity/CoursePlaceTest.java, src/test/java/com/prgrms/p2p/domain/course/entity/CourseTest.java, src/test/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImplTest.java
- 나와 타인의 코스 조회 기능 추가
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173] 나와 타인의 코스 조회 기능 추가

src/main/java/com/prgrms/p2p/domain/comment/service/PlaceCommentService.java, src/test/java/com/prgrms/p2p/domain/comment/service/PlaceCommentServiceTest.java
- 여기에 내용 기재
- 세부적으로 막만들다가 이럴필요가 있을까 해서 의미적으로 엇나가는 예외만 수정 했습니다.
- 여기에 내용 기재
=> [P2P-183] PlaceComment 예외처리 

src/main/java/com/prgrms/p2p/domain/place/controller/PlaceController.java, src/main/java/com/prgrms/p2p/domain/place/service/PlaceService.java, src/main/java/com/prgrms/p2p/domain/user/config/config/WebSecurityConfig.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-66] 장소 등록에 대한 권한 및 로직 수정, 장소 스웨거를 등록했습니다.

src/main/java/com/prgrms/p2p/domain/comment/controller/MergeCommentController.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-127] 종합 댓글 조회 컨트롤러에 예외 처리 부분을 추가했습니다.

src/main/java/com/prgrms/p2p/domain/comment/controller/PlaceCommentController.java
- 여기에 내용 기재
- 여기저기 찾아다니며 스웨거 참고하며 추가했습니다.. 틀린거 있으면 말씀해주세요
- 여기에 내용 기재
=> [P2P-186] 장소 댓글에 대한 스웨거 추가

src/main/java/com/prgrms/p2p/domain/course/util/CoursePlaceConverter.java, src/main/java/com/prgrms/p2p/domain/place/entity/Address.java, src/main/java/com/prgrms/p2p/domain/place/entity/PhoneNumber.java, src/main/java/com/prgrms/p2p/domain/place/entity/Place.java, src/main/java/com/prgrms/p2p/domain/place/service/PlaceService.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-184] 장소 관련된 예외 처리를 추가합니다.

src/main/java/com/prgrms/p2p/domain/course/util/CoursePlaceConverter.java, src/main/java/com/prgrms/p2p/domain/place/entity/PhoneNumber.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173]요청사항반영

src/main/java/com/prgrms/p2p/domain/comment/controller/CourseCommentController.java, src/main/java/com/prgrms/p2p/domain/comment/service/CourseCommentService.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-177] 코스 댓글 예외 관리 및 스웨거 추가

src/main/java/com/prgrms/p2p/domain/comment/service/PlaceCommentService.java
- 여기에 내용 기재
- 이미 삭제된 경우가 있어서 추가했습니다.
- 여기에 내용 기재
=> [P2P-183] 장소 댓글 삭제에서 이미 삭제된 경우 처리 추가

src/main/java/com/prgrms/p2p/domain/comment/util/CommentConverter.java
- 여기에 내용 기재
- 지니님 api 테스트 했을 때 문제가 있어서 수정했습니다.
- 여기에 내용 기재
=> [P2P-187] 장소댓글 id와 유저 id와 중복에 따라 Converter 수정

src/main/java/com/prgrms/p2p/domain/place/entity/PhoneNumber.java, src/test/java/com/prgrms/p2p/domain/place/entity/AddressTest.java, src/test/java/com/prgrms/p2p/domain/place/entity/PhoneNumberTest.java, src/test/java/com/prgrms/p2p/domain/place/entity/PlaceTest.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-65] 프론트에서 요청한 장소 요구사항 변경에 따른 테스트 변경

src/main/java/com/prgrms/p2p/domain/course/service/CourseQueryService.java, src/test/java/com/prgrms/p2p/domain/course/service/CourseQueryServiceTest.java
- 코스 조회 수정 및 테스트 추가
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-63] 코스 조회 수정 및 테스트 추가

src/main/java/com/prgrms/p2p/domain/comment/service/PlaceCommentService.java
- 여기에 내용 기재
- 대댓글에 대댓글 예외처리 수정입니다.
- 여기에 내용 기재
=> [P2P-187] 대댓글에 댓글작성시 예외처리 수정

src/test/java/com/prgrms/p2p/domain/place/service/PlaceServiceTest.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-67] 장소 검색조건 추가에 대한 테스트를 추가, 수정했습니다.

src/main/java/com/prgrms/p2p/domain/place/controller/PlaceController.java, src/main/java/com/prgrms/p2p/domain/place/dto/DetailPlaceResponse.java, src/main/java/com/prgrms/p2p/domain/place/dto/SearchPlaceDto.java, src/main/java/com/prgrms/p2p/domain/place/dto/SummaryPlaceResponse.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-191] 장소 컨트롤러 및 요청, 응답에 스웨거를 적용합니다.

src/main/java/com/prgrms/p2p/domain/comment/dto/CourseCommentDto.java, src/main/java/com/prgrms/p2p/domain/comment/dto/CourseCommentForQueryDsl.java, src/main/java/com/prgrms/p2p/domain/comment/dto/CourseCommentResponse.java, src/main/java/com/prgrms/p2p/domain/comment/dto/CreateCommentRequest.java, src/main/java/com/prgrms/p2p/domain/comment/dto/MergeCommentResponse.java, src/main/java/com/prgrms/p2p/domain/place/dto/SearchPlaceDto.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-190] 코스 댓글 부분 스웨거를 이용한 필드 설명 추가 및 장소 댓글과 dto 통합을 위한 사전작업.

src/main/java/com/prgrms/p2p/domain/comment/service/PlaceCommentService.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-187] 장소댓글 수정 및 삭제 에 대한 예외처리 수정

src/test/java/com/prgrms/p2p/domain/comment/service/CourseCommentServiceTest.java, src/test/java/com/prgrms/p2p/domain/comment/service/MergeCommentServiceTest.java
…y 변환 작업 테스트, 코스 - 댓글 미 매칭시 예외 반환)
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-175] 코스 댓글 테스트 추가 (대댓글 삭제시 로직 버그 픽스한 부분 테스트 추가, 코스 - 댓글간 언매칭시 예외 반환)

src/main/java/com/prgrms/p2p/domain/course/entity/Course.java, src/main/java/com/prgrms/p2p/domain/course/exception/CoursePlaceAndImageSizeNotEqualException.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseService.java, src/main/java/com/prgrms/p2p/domain/course/util/CourseConverter.java, src/test/java/com/prgrms/p2p/domain/course/entity/CourseTest.java, src/test/java/com/prgrms/p2p/domain/course/service/CourseQueryServiceTest.java
- 코스 목록 조회에 spot 빠진거 추가
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-63] 코스 목록 조회에 spot 빠진거 추가

src/main/java/com/prgrms/p2p/domain/course/util/CourseConverter.java
- 특정 검색 키워드에서 "message": "Index 0 out of bounds for length 0" 발생
- 조건에 맞는 course의 coursePlaces에서 썸네일로 허락된 것이 없을 경우 첫번째 index의 이미지를 사용하는 로직에서
- 코스에 등록된 장소 자체가 존재하지 않아 이러한 오류가 발생한 것으로 사료됌
- coursePlace의 size가 0일 경우 null을 반환하는 로직 추가
- 여기에 내용 기재
=> [P2P-194] 코스 컨버터에서 pickThumnail 버그 수정했습니다.

src/test/java/com/prgrms/p2p/domain/place/entity/PhoneNumberTest.java, src/test/java/com/prgrms/p2p/domain/place/entity/PlaceTest.java, src/test/java/com/prgrms/p2p/domain/place/repository/PlaceSearchRepositoryTest.java, src/test/java/com/prgrms/p2p/domain/place/service/PlaceServiceTest.java
- 여기에 내용 기재
- 장소 관련 테스트 RuntimeException에서 세분화된 예외를 반환을 검증할 수 있도록 처리했습니다.
- 여기에 내용 기재
=> [P2P-195] 장소 관련 테스트 예외 변경

src/test/java/com/prgrms/p2p/domain/comment/service/PlaceCommentServiceTest.java
- 여기에 내용 기재
- 수정내용 테스트부분 추가
- 여기에 내용 기재
=> [P2P-114] 예외처리 수정했던 부분 테스트 코드 수정및 추가

src/main/java/com/prgrms/p2p/domain/course/service/CourseService.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173] validation 수정

src/main/java/com/prgrms/p2p/domain/course/repository/CoursePlaceRepository.java, src/main/java/com/prgrms/p2p/domain/course/service/CoursePlaceService.java, src/main/java/com/prgrms/p2p/domain/course/util/CourseConverter.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173]지워진 코스 장소는 안 보이게 수정

src/main/java/com/prgrms/p2p/domain/course/repository/CoursePlaceRepository.java, src/main/java/com/prgrms/p2p/domain/course/service/CoursePlaceService.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseService.java, src/main/java/com/prgrms/p2p/domain/course/util/CourseConverter.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-000] 메인으로 머지

src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173] 코스 swagger 추가

src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173]검색 조건 변경

src/test/java/com/prgrms/p2p/domain/comment/service/CourseCommentServiceTest.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-196] 코스 댓글 관련 테스트 예외 변경

src/test/java/com/prgrms/p2p/domain/comment/repository/SearchPlaceCommentRepositoryImplTest.java, src/test/java/com/prgrms/p2p/domain/comment/service/SearchPlaceCommentServiceTest.java
- 여기에 내용 기재
- 테스트 테스트
- 여기에 내용 기재
=> [P2P-118] 장소에 관련된 댓글 가져오기 테스트 추가

src/main/java/com/prgrms/p2p/domain/course/entity/Sorting.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-41] 키워드를 포함한 장소를 포함한 코스 혹은 제목에 키워드가 포함된 코스 검색기능 리팩토링

src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173]검색 조건 수정

src/main/java/com/prgrms/p2p/domain/course/entity/Sorting.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-000] 메인 머지

src/main/java/com/prgrms/p2p/domain/course/dto/CoursePlaceResponse.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseService.java, src/main/java/com/prgrms/p2p/domain/course/util/CourseConverter.java, src/main/java/com/prgrms/p2p/domain/course/util/CoursePlaceConverter.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173] 코스 수정

src/main/java/com/prgrms/p2p/domain/course/repository/CourseSearchRepositoryImpl.java
- 인기순으로만 정렬하면 뭔가,, 중복되는 결과를 가져오는 경우가 있어서 최신순 정렬도 넣어주었습니다. 
- 최신순으로 해서 최신순이 두 번이 걸려있어도 order by 조건에는 하나만 나가서 괜찮을듯 싶어요
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173] 인기가 같은 경우 정렬 조건 추가

src/main/java/com/prgrms/p2p/domain/course/service/CourseService.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173]수정 변경

src/main/java/com/prgrms/p2p/domain/user/config/security/JwtAuthenticationFilter.java
- 여기에 내용 기재
- jwt 필터에서 예외를 찾아서 처리했습니다.
> 일단 제 로컬에서는 다른 토큰값을 넣으면 이제 401 에러를 뱉는데 다른 분들도 확인 부탁드립니다.
- 여기에 내용 기재
=> [P2P-22] 토큰 에러 500으로 나오는 문제 해결

.gitignore, src/main/java/com/prgrms/p2p/domain/common/exception/ExceptionAdvice.java, src/main/java/com/prgrms/p2p/domain/common/log/LogAspect.java, src/main/java/com/prgrms/p2p/domain/common/log/LogExecutionTime.java, src/main/java/com/prgrms/p2p/domain/common/log/LogInterceptor.java, src/main/java/com/prgrms/p2p/domain/user/config/config/InterceptorConfig.java, src/main/resources/logback-spring.xml, src/test/resources/application.yaml
- 로그를 적재하기 위한 파일을 기재합니다.
- `LogExecutionTime` 를 붙여서 성능 측정을 할 수 있습니다.
=> [P2P-188] 로그관리 파일 추가

src/main/java/com/prgrms/p2p/domain/place/entity/PhoneNumber.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-55]  전화번호 검증 로직 삭제(안심 번호등의 이슈로 인하여)

src/main/java/com/prgrms/p2p/domain/place/repository/PlaceSearchRepositoryImpl.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-56] 장소 인기순 좋아요 동일할 때 정렬조건 추가

src/main/java/com/prgrms/p2p/domain/place/entity/PhoneNumber.java, src/main/java/com/prgrms/p2p/domain/place/repository/PlaceSearchRepositoryImpl.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-00] 배포(정렬기준 이슈)

src/main/java/com/prgrms/p2p/domain/comment/repository/CourseCommentRepository.java, src/main/java/com/prgrms/p2p/domain/course/dto/DetailCourseResponse.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseQueryService.java, src/main/java/com/prgrms/p2p/domain/course/util/CourseConverter.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173] 코스 상세 조회에 댓글 개수 추가

src/main/java/com/prgrms/p2p/domain/comment/repository/CourseCommentRepository.java, src/main/java/com/prgrms/p2p/domain/course/dto/DetailCourseResponse.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseQueryService.java, src/main/java/com/prgrms/p2p/domain/course/util/CourseConverter.java, src/main/java/com/prgrms/p2p/domain/place/repository/PlaceSearchRepositoryImpl.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-000] 메인으로 머지 

src/main/java/com/prgrms/p2p/domain/comment/repository/PlaceCommentRepository.java, src/main/java/com/prgrms/p2p/domain/place/dto/DetailPlaceResponse.java, src/main/java/com/prgrms/p2p/domain/place/service/PlaceService.java, src/main/java/com/prgrms/p2p/domain/place/util/PlaceConverter.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-68] 장소 상세조회 반환값 필드 2개(카카오 맵 아이디, 댓글 개수) 추가

src/main/java/com/prgrms/p2p/P2pApplication.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173]타임존 설정

src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseQueryService.java, src/test/java/com/prgrms/p2p/domain/course/service/CourseQueryServiceTest.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173] 북마크한 코스 수정

src/main/java/com/prgrms/p2p/P2pApplication.java, src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseQueryService.java, src/test/java/com/prgrms/p2p/domain/course/service/CourseQueryServiceTest.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-000] 메인 머지 

src/main/java/com/prgrms/p2p/domain/course/controller/CourseController.java, src/main/java/com/prgrms/p2p/domain/course/repository/CourseRepository.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseQueryService.java, src/main/java/com/prgrms/p2p/domain/place/repository/PlaceRepository.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-173] fetch 조인으로 인한 오류 해결

src/test/java/com/prgrms/p2p/domain/comment/service/SearchPlaceCommentServiceTest.java
- 잘못된 getter 명에 따른 수정
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-118] test: 잘못된 getter  수정

src/main/java/com/prgrms/p2p/domain/comment/repository/CourseCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/repository/PlaceCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchCourseCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchCourseCommentRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchPlaceCommentRepository.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchPlaceCommentRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/course/dto/DetailCourseResponse.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseQueryService.java, src/main/java/com/prgrms/p2p/domain/course/util/CourseConverter.java
- 코스(장소) 상세에서 댓글 개수 조회하는 쿼리가 visibility  = True 엢어서 추가함
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-199] 코스(장소) 상세 - 댓글 간 갯수 상이한 점 수정

src/main/java/com/prgrms/p2p/domain/comment/repository/SearchCourseCommentRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/comment/repository/SearchPlaceCommentRepositoryImpl.java, src/main/java/com/prgrms/p2p/domain/place/dto/DetailPlaceResponse.java, src/main/java/com/prgrms/p2p/domain/place/service/PlaceService.java, src/main/java/com/prgrms/p2p/domain/place/util/PlaceConverter.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-199] 댓글 개수 상이 내용 수정

src/main/java/com/prgrms/p2p/domain/comment/util/CommentConverter.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-199] 댓글 상세정보에서 삭제된 댓글까지 카운트 되는 점 수정

src/main/java/com/prgrms/p2p/domain/place/dto/DetailPlaceResponse.java, src/main/java/com/prgrms/p2p/domain/place/util/PlaceConverter.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-200] feat: 장소 상세 이미지 여러개 + 이미지 개수

src/main/java/com/prgrms/p2p/domain/comment/entity/Comment.java, src/main/java/com/prgrms/p2p/domain/comment/service/CourseCommentService.java, src/main/java/com/prgrms/p2p/domain/comment/service/PlaceCommentService.java, src/main/java/com/prgrms/p2p/domain/course/entity/Course.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseService.java, src/main/java/com/prgrms/p2p/domain/user/config/config/WebSecurityConfig.java, src/main/java/com/prgrms/p2p/domain/user/entity/Authority.java, src/main/java/com/prgrms/p2p/domain/user/util/UserConverter.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-201] 관리자가 게시물의 삭제권한을 가집니다.

src/main/java/com/prgrms/p2p/domain/user/dto/LoginResponse.java, src/main/java/com/prgrms/p2p/domain/user/dto/UserDetailResponse.java, src/main/java/com/prgrms/p2p/domain/user/util/UserConverter.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-201] 응답에 유저의 권한 정보 추가

src/main/java/com/prgrms/p2p/domain/user/config/config/WebSecurityConfig.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-201] fix: 시큐리티 사용권한 수정

build.gradle, src/main/java/com/prgrms/p2p/domain/user/config/config/MailConfig.java, src/main/java/com/prgrms/p2p/domain/user/controller/UserController.java, src/main/java/com/prgrms/p2p/domain/user/dto/FindPasswordRequest.java, src/main/java/com/prgrms/p2p/domain/user/dto/ValidateCertPasswordRequest.java, src/main/java/com/prgrms/p2p/domain/user/service/CertNumberService.java, src/main/java/com/prgrms/p2p/domain/user/service/UserService.java, src/main/java/com/prgrms/p2p/domain/user/util/GenerateCertPassword.java, src/main/java/com/prgrms/p2p/domain/user/util/MailBodyUtil.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-202] 비밀번호 찾기 : 이메일로 인증번호를 요청후 수정하는 로직 추가

src/main/java/com/prgrms/p2p/domain/course/entity/Course.java, src/main/java/com/prgrms/p2p/domain/place/entity/Place.java, src/main/java/com/prgrms/p2p/domain/user/entity/User.java
- 여기에 내용 기재
- 여기에 내용 기재
- 여기에 내용 기재
=> [P2P-204] N+1 문제 해결

src/main/java/com/prgrms/p2p/domain/comment/service/CourseCommentService.java, src/main/java/com/prgrms/p2p/domain/comment/service/PlaceCommentService.java, src/main/java/com/prgrms/p2p/domain/course/service/CourseService.java, src/main/java/com/prgrms/p2p/domain/user/dto/OtherUserDetailResponse.java, src/main/java/com/prgrms/p2p/domain/user/dto/UserDetailResponse.java, src/main/java/com/prgrms/p2p/domain/user/entity/Grade.java, src/main/java/com/prgrms/p2p/domain/user/entity/Point.java, src/main/java/com/prgrms/p2p/domain/user/entity/User.java, src/main/java/com/prgrms/p2p/domain/user/util/GradeUtil.java, src/main/java/com/prgrms/p2p/domain/user/util/UserConverter.java
- 여기에 내용 기재
- User에 각 점수(Score)를 추가해서 게시글 작성시 + 50점, 댓글 생성시 +10점을 얻도록 수정했습니다.
- 만약 코스 글을 삭제하거나 댓글을 삭제하면 삭제를 누른 유저에게 각각 -50, -10 이 적용되게 했습니다.
- Score는 아무리 적어도 0점이 최솟값입니다.
- 내 유저 정보와 타인의 유저정보를 가져올때 각 Score값에 대한 등급(Grade)을 만들어서 브론즈, 실버, 골드, 플레티넘, 다이아, 마스터 6단계로 나누었고 각 등급 임계값은 0 ~ 99, 10 ~ 299, 300 ~ 499, 500 ~ 999,1000 ~ 2999, 3000 ~ 으로 나누었습니다.
- 여기에 내용 기재
=> [P2P-205] User 점수 및 등급 추가
